In [1]:
from pymongo import MongoClient

In [2]:
client = MongoClient("mongodb+srv://XXXXXXX")
db = client.sample_mflix

In [4]:
for idx, item in enumerate(db.movies.find()):
    print(item)
    print('----')
    if idx == 5:
        break

{'_id': ObjectId('573a1390f29313caabcd4eaf'), 'plot': 'A woman, with the aid of her police officer sweetheart, endeavors to uncover the prostitution ring that has kidnapped her sister, and the philanthropist who secretly runs it.', 'genres': ['Crime', 'Drama'], 'runtime': 88, 'cast': ['Jane Gail', 'Ethel Grandin', 'William H. Turner', 'Matt Moore'], 'num_mflix_comments': 1, 'poster': 'https://m.media-amazon.com/images/M/MV5BYzk0YWQzMGYtYTM5MC00NjM2LWE5YzYtMjgyNDVhZDg1N2YzXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_SY1000_SX677_AL_.jpg', 'title': 'Traffic in Souls', 'lastupdated': '2015-09-15 02:07:14.247000000', 'languages': ['English'], 'released': datetime.datetime(1913, 11, 24, 0, 0), 'directors': ['George Loane Tucker'], 'rated': 'TV-PG', 'awards': {'wins': 1, 'nominations': 0, 'text': '1 win.'}, 'year': 1913, 'imdb': {'rating': 6.0, 'votes': 371, 'id': 3471}, 'countries': ['USA'], 'type': 'movie', 'tomatoes': {'viewer': {'rating': 3.0, 'numReviews': 85, 'meter': 57}, 'dvd': datetime.datetime(2008, 8, 26, 0, 0), 'lastUpdated': datetime.datetime(2015, 8, 10, 18, 33, 55)}}
----
{'_id': ObjectId('573a1390f29313caabcd6223'), 'plot': "Gwen's family is rich, but her parents ignore her and most of the servants push her around, so she is lonely and unhappy. Her father is concerned only with making money, and her mother ...", 'genres': ['Comedy', 'Drama', 'Family'], 'runtime': 65, 'cast': ['Mary Pickford', 'Madlaine Traverse', 'Charles Wellesley', 'Gladys Fairbanks'], 'title': 'The Poor Little Rich Girl', 'fullplot': "Gwen's family is rich, but her parents ignore her and most of the servants push her around, so she is lonely and unhappy. Her father is concerned only with making money, and her mother cares only about her social position. But one day a servant's irresponsibility creates a crisis that causes everyone to rethink what is important to them.", 'languages': ['English'], 'released': datetime.datetime(1917, 3, 5, 0, 0), 'directors': ['Maurice Tourneur'], 'writers': ['Eleanor Gates (play)', 'Frances Marion (scenario)'], 'awards': {'wins': 1, 'nominations': 0, 'text': '1 win.'}, 'lastupdated': '2015-07-27 00:11:31.387000000', 'year': 1917, 'imdb': {'rating': 6.9, 'votes': 884, 'id': 8443}, 'countries': ['USA'], 'type': 'movie', 'tomatoes': {'viewer': {'rating': 3.9, 'numReviews': 137, 'meter': 77}, 'production': 'Artcraft', 'lastUpdated': datetime.datetime(2015, 8, 21, 18, 0, 25)}, 'num_mflix_comments': 0}
----
{'_id': ObjectId('573a1391f29313caabcd6ea2'), 'plot': 'The simple-minded son of a rich financier must find his own way in the world.', 'genres': ['Comedy'], 'runtime': 77, 'cast': ['Edward Jobson', 'Beulah Booker', 'Edward Connelly', 'Edward Alexander'], 'num_mflix_comments': 0, 'poster': 'https://m.media-amazon.com/images/M/MV5BZDNiODA3NzQtNTBmZS00NTM3LWJlOGMtMDg2NzFiNDU2M2M3XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_SY1000_SX677_AL_.jpg', 'title': 'The Saphead', 'fullplot': "Nick Van Alstyne owns the Henrietta silver mine and is very rich. His son Bertie is naive and spoiled. His daughter Rose is married to shady investor Mark. Mark wrecks Bertie's wedding plans by making him take the blame for Mark's illegitimate daughter. Mark also nearly ruins the family business by selling off Henrietta stock at too low a price. Bertie, of all people, must come to the rescue on the trading floor.", 'countries': ['USA'], 'released': datetime.datetime(1920, 9, 1, 0, 0), 'directors': ['Herbert Blachè', 'Winchell Smith'], 'writers': ['Bronson Howard (original play "The Henrietta")', 'Victor Mapes (play)', 'June Mathis (scenario)', 'Winchell Smith (play)'], 'awards': {'wins': 0, 'nominations': 1, 'text': '1 nomination.'}, 'lastupdated': '2015-06-20 00:38:08.303000000', 'year': 1920, 'imdb': {'rating': 6.2, 'votes': 1020, 'id': 11652}, 'type': 'movie', 'tomatoes': {'viewer': {'rating': 3.3, 'numReviews': 435, 'meter': 49}, 'dvd': datetime.datetime(2000, 1, 11, 0, 0), 'lastUpdated': datetime.datetime(2015, 6, 23, 19, 23, 34)}}
----
{'_id': ObjectId('573a1390f29313caabcd446f'), 'plot': "A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film...", 'genres': ['Short', 'Drama'], 'runtime': 14, 'cast': ['Frank Powell', 'Grace Henderson', 'James Kirkwood', 'Linda Arvidson'], 'num_mflix_comments': 1, 'title': 'A Corner in Wheat', 'fullplot': "A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film continues to contrast the ironic differences between the lives of those who work to grow the wheat and the life of the man who dabbles in its sale for profit.", 'languages': ['English'], 'released': datetime.datetime(1909, 12, 13, 0, 0), 'directors': ['D.W. Griffith'], 'rated': 'G', 'awards': {'wins': 1, 'nominations': 0, 'text': '1 win.'}, 'lastupdated': '2015-08-13 00:46:30.660000000', 'year': 1909, 'imdb': {'rating': 6.6, 'votes': 1375, 'id': 832}, 'countries': ['USA'], 'type': 'movie', 'tomatoes': {'viewer': {'rating': 3.6, 'numReviews': 109, 'meter': 73}, 'lastUpdated': datetime.datetime(2015, 5, 11, 18, 36, 53)}}
----
{'_id': ObjectId('573a1391f29313caabcd6e2a'), 'plot': "A newly wedded couple attempt to build a house with a prefabricated kit, unaware that a rival sabotaged the kit's component numbering.", 'genres': ['Short', 'Comedy'], 'runtime': 25, 'cast': ['Buster Keaton', 'Sybil Seely'], 'num_mflix_comments': 0, 'title': 'One Week', 'fullplot': "Buster and Sybil exit a chapel as newlyweds. Among the gifts is a portable house you easily put together in one week. It doesn't help that Buster's rival for Sybil switches the numbers on the crates containing the house parts.", 'languages': ['English'], 'released': datetime.datetime(1920, 9, 1, 0, 0), 'directors': ['Edward F. Cline', 'Buster Keaton'], 'rated': 'TV-G', 'awards': {'wins': 1, 'nominations': 0, 'text': '1 win.'}, 'lastupdated': '2015-05-07 01:07:01.633000000', 'year': 1920, 'imdb': {'rating': 8.3, 'votes': 3942, 'id': 11541}, 'countries': ['USA'], 'type': 'movie', 'tomatoes': {'viewer': {'rating': 4.3, 'numReviews': 752, 'meter': 91}, 'lastUpdated': datetime.datetime(2015, 9, 13, 18, 22, 19)}}
----
{'_id': ObjectId('573a1390f29313caabcd56df'), 'plot': 'An immigrant leaves his sweetheart in Italy to find a better life across the sea in the grimy slums of New York. They are eventually reunited and marry. But life in New York is hard and ...', 'genres': ['Drama'], 'runtime': 78, 'rated': 'PASSED', 'cast': ['George Beban', 'Clara Williams', 'J. Frank Burke', 'Leo Willis'], 'title': 'The Italian', 'fullplot': 'An immigrant leaves his sweetheart in Italy to find a better life across the sea in the grimy slums of New York. They are eventually reunited and marry. But life in New York is hard and tragedy tarnishes their dream of a better life in the new world.', 'languages': ['English'], 'released': datetime.datetime(1915, 1, 1, 0, 0), 'directors': ['Reginald Barker'], 'writers': ['Thomas H. Ince (story)', 'C. Gardner Sullivan (story)'], 'awards': {'wins': 1, 'nominations': 0, 'text': '1 win.'}, 'lastupdated': '2015-07-27 00:07:43.230000000', 'year': 1915, 'imdb': {'rating': 6.4, 'votes': 175, 'id': 5557}, 'countries': ['USA'], 'type': 'movie', 'tomatoes': {'viewer': {'rating': 4.0, 'numReviews': 204, 'meter': 60}, 'dvd': datetime.datetime(2008, 8, 26, 0, 0), 'lastUpdated': datetime.datetime(2015, 7, 24, 19, 30, 2)}, 'num_mflix_comments': 0}
----

In [ ]:
# find Italian movies in Italian and sort them by year, retrieve the first 5
query = {"countries" : "Italy", "languages" : "Italian"}
prop = {"_id":0, "title":1, "year":1, "runtime":1, "languages":1, "fullplot":1}
res = db.movies.find(query, prop)

list(res.sort({'year':-1}).limit(5))

[{'runtime': 86,
  'title': 'La scelta',
  'fullplot': 'A childless couple struggle in the aftermath of a sexual assault leaves the woman pregnant.',
  'languages': ['Italian'],
  'year': 2015},
 {'runtime': 106,
  'title': 'Blood of My Blood',
  'languages': ['Italian'],
  'year': 2015},
 {'runtime': 107,
  'title': 'Mediterranea',
  'languages': ['French', 'Italian', 'English', 'Arabic'],
  'year': 2015},
 {'runtime': 106,
  'title': 'Mia Madre',
  'fullplot': 'Margherita, a director in the middle of an existential crisis, has to deal with the inevitable and still unacceptable loss of her mother.',
  'languages': ['Italian', 'English'],
  'year': 2015},
 {'runtime': 87,
  'title': 'Lost and Beautiful',
  'fullplot': "The foolish servant Pulcinella is sent from the depths of Mt. Vesuvius to present-day Campania to honor the last wishes of the poor shepherd Tommaso: his mission is to save a young buffalo called Sarchiapone. Pulcinella finds the animal at the former royal palace of Carditello, where Tommaso had looked after the ruined Bourbon estate in the heart of the Land of Fires. He takes the buffalo off to the north and the two servants, man and beast, travel through a beautiful and lost Italy, but their long journey's end does not bring what they were hoping for.",
  'languages': ['Italian'],
  'year': 2015}]

In [ ]:
# find movies rated as R with Meryl Streep or Charlize Theron
query = {"$or" : [{"cast":"Meryl Streep"}, {"cast" : "Charlize Theron"}], "rated":"R"}
prop = {"_id":0, "title":1, "year":1, "cast":1, "rated":1}
res = db.movies.find(query, prop)
list(res.limit(3))

[{'rated': 'R',
  'cast': ['Alan Alda', 'Barbara Harris', 'Meryl Streep', 'Rip Torn'],
  'title': 'The Seduction of Joe Tynan',
  'year': 1979},
 {'rated': 'R',
  'cast': ['Meryl Streep', 'Jeremy Irons', 'Hilton McRae', 'Emily Morgan'],
  'title': "The French Lieutenant's Woman",
  'year': 1981},
 {'year': 1982,
  'rated': 'R',
  'title': "Sophie's Choice",
  'cast': ['Meryl Streep', 'Kevin Kline', 'Peter MacNicol', 'Rita Karin']}]

In [ ]:
# find movies with Charlize Theron with year <= 2015
query = {"cast" : "Charlize Theron", "year":{"$lte":2015}}
prop = {"_id":0, "title":1, "year":1, "cast":1, "rated":1}
res = db.movies.find(query, prop)
list(res.limit(3))

[{'year': 1997,
  'rated': 'R',
  'title': "The Devil's Advocate",
  'cast': ['Keanu Reeves', 'Al Pacino', 'Charlize Theron', 'Jeffrey Jones']},
 {'rated': 'PG',
  'cast': ['Charlize Theron', 'Bill Paxton', 'Rade Serbedzija', 'Peter Firth'],
  'title': 'Mighty Joe Young',
  'year': 1998},
 {'year': 1999,
  'rated': 'PG-13',
  'title': 'The Cider House Rules',
  'cast': ['Tobey Maguire', 'Charlize Theron', 'Delroy Lindo', 'Paul Rudd']}]

In [ ]:
# find moview that are not movie-type movie and with num_mflix_comments > 0
query = {"type": {"$ne" : "movie"}, "num_mflix_comments": {"$gt" : 0}}
prop = {"_id":0, "title":1, "type":1, "cast":1, "num_mflix_comments":1}
res = db.movies.find(query, prop)
list(res.limit(3))

[{'cast': ['Joanne Woodward', 'Sally Field'],
  'num_mflix_comments': 1,
  'title': 'Sybil',
  'type': 'series'},
 {'cast': ['Robert Powell',
   'Anne Bancroft',
   'Ernest Borgnine',
   'James Farentino'],
  'num_mflix_comments': 1,
  'title': 'Jesus of Nazareth',
  'type': 'series'},
 {'cast': ['Olivia Cole', 'Robert Reed', 'John Amos', 'Madge Sinclair'],
  'num_mflix_comments': 3,
  'title': 'Roots',
  'type': 'series'}]

In [ ]:
# find movies with imdb rating > 9
query = {"imdb.rating": {"$gt" : 9}}
prop = {"_id":0, "title":1, "type":1, "cast":1, "imdb":1}
res = db.movies.find(query, prop)
list(res.limit(3))

[{'imdb': {'rating': 9.2, 'votes': 1038358, 'id': 68646},
  'title': 'The Godfather',
  'type': 'movie',
  'cast': ['Marlon Brando',
   'Al Pacino',
   'James Caan',
   'Richard S. Castellano']},
 {'imdb': {'rating': 9.1, 'votes': 700857, 'id': 71562},
  'title': 'The Godfather: Part II',
  'type': 'movie',
  'cast': ['Al Pacino', 'Robert Duvall', 'Diane Keaton', 'Robert De Niro']},
 {'cast': ['James Mason', 'Viola Dana', 'Byron Haskin', 'Colleen Moore'],
  'title': 'Hollywood',
  'imdb': {'rating': 9.1, 'votes': 511, 'id': 80230},
  'type': 'series'}]

**Aggregations**

In [ ]:
# how many movies are in the collection?

group_stg = {"$group":{"_id":"null", "count":{"$sum":1}}}
res = db.movies.aggregate([group_stg])
list(res)

[{'_id': 'null', 'count': 21349}]

In [ ]:
# count the movies with Meryl Streep
match_stg = {"$match" : {"cast":"Meryl Streep"}}
group_stg = {"$group":{"_id":"null", "count":{"$sum":1}}}
res = db.movies.aggregate([match_stg, group_stg])
list(res)

[{'_id': 'null', 'count': 42}]

In [ ]:
# count the Amerian movies for each rating
match_stg = {"$match" : {"countries":"USA"}}
group_stg = {"$group":{"_id":"$rated", "count":{"$sum":1}}}
res = db.movies.aggregate([match_stg, group_stg])
list(res)

[{'_id': 'TV-14', 'count': 65},
 {'_id': 'GP', 'count': 22},
 {'_id': 'TV-Y7', 'count': 3},
 {'_id': 'Not Rated', 'count': 1},
 {'_id': 'M', 'count': 23},
 {'_id': 'TV-PG', 'count': 64},
 {'_id': None, 'count': 2218},
 {'_id': 'PG-13', 'count': 1942},
 {'_id': 'PASSED', 'count': 169},
 {'_id': 'PG', 'count': 1424},
 {'_id': 'TV-G', 'count': 53},
 {'_id': 'Approved', 'count': 4},
 {'_id': 'G', 'count': 373},
 {'_id': 'R', 'count': 3902},
 {'_id': 'AO', 'count': 1},
 {'_id': 'APPROVED', 'count': 610},
 {'_id': 'TV-MA', 'count': 47}]

In [ ]:
# find top 5 Italian movies with the larger cast
# note: in the initial filter I remove the movies for which there is no cast
match_stg = {"$match" : {"countries":"Italy", "cast":{"$exists":"true"}}}
project_stg = {"$project" : {"_id":0, "title":1, "countries":1, "ncast": {"$size":"$cast"}}}
sort_stg = {"$sort": {"ncast":-1}}
limit_stg = {"$limit":5}
res = db.movies.aggregate([match_stg, project_stg, sort_stg, limit_stg])
list(res)

[{'title': 'Ossessione', 'countries': ['Italy'], 'ncast': 4},
 {'title': 'The Testimony', 'countries': ['Italy'], 'ncast': 4},
 {'title': 'The Bandit', 'countries': ['Italy'], 'ncast': 4},
 {'countries': ['Italy', 'Spain'],
  'title': 'The Siege of the Alcazar',
  'ncast': 4},
 {'title': "Everybody's Woman", 'countries': ['Italy'], 'ncast': 4}]

Create a dataframe with films for which "fullplot" is available

According to a similarity criterion on texts, find the top 5 movies with a plot similar to "Casablanca"

In [ ]:
import pandas as pd
it_movies = db.movies.find({"title" : "Casablanca"}, {"_id":0, "title":1, "year":1, "runtime":1, "fullplot":1})
df_it_movies = pd.DataFrame(it_movies)

df_it_movies

,runtime,title,fullplot,year
0,102,Casablanca,"In World War II Casablanca, Rick Blaine, exile...",1942

In [30]:
target_plot = db.movies.find({"title" : "Casablanca"}, {"_id":0, "title":1, "fullplot":1})[0]['fullplot']

In [32]:
target_plot

"In World War II Casablanca, Rick Blaine, exiled American and former freedom fighter, runs the most popular nightspot in town. The cynical lone wolf Blaine comes into the possession of two valuable letters of transit. When Nazi Major Strasser arrives in Casablanca, the sycophantic police Captain Renault does what he can to please him, including detaining a Czechoslovak underground leader Victor Laszlo. Much to Rick's surprise, Lazslo arrives with Ilsa, Rick's one time love. Rick is very bitter towards Ilsa, who ran out on him in Paris, but when he learns she had good reason to, they plan to run off together again using the letters of transit. Well, that was their original plan...."

In [26]:
df_plot = pd.DataFrame(db.movies.find({ "fullplot": { '$exists': True } }, {"_id":0, "title":1, "fullplot":1}))

In [27]:
df_plot

,title,fullplot
0,The Great Train Robbery,Among the earliest existing films in American ...
1,A Corner in Wheat,"A greedy tycoon decides, on a whim, to corner ..."
2,"Winsor McCay, the Famous Cartoonist of the N.Y...",Cartoonist Winsor McCay agrees to create a lar...
3,Gertie the Dinosaur,Winsor Z. McCay bets another cartoonist that h...
4,The Perils of Pauline,Young Pauline is left a lot of money when her ...
...,...,...
19847,Heil,The African-German writer Sebastian Klein is o...
19848,The Laundryman,A-Gu enlists a group of contract killers in th...
19849,The Red Spider,"Karol, an ordinary young man, runs into a much..."
19850,Our Loved Ones,Guy's tragic death is a shock for the Leblanc ...
19851,Scenes of a Sexual Nature,Various Londeners meet people in Hampstead Hea...

In [33]:
plots = list(df_plot['fullplot'])

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Preprocessing and Feature Extraction using TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english')  # Remove stop words
X = tfidf_vectorizer.fit_transform(plots)  # Convert text data to TF-IDF vectors
target = tfidf_vectorizer.transform([target_plot])

In [96]:
print(X.shape)
print(target.shape)

(19852, 57486)
(1, 57486)

In [92]:
import numpy as np
from scipy.spatial.distance import cosine, euclidean
distances = []

for idx, plot_cand in enumerate(X):
    c = np.squeeze(plot_cand.toarray())
    t = np.squeeze(target.toarray())
    dist = 1 - cosine(c, t)
    dist_e = euclidean(c, t)
    title = df_plot.at[idx, 'title']
    distances.append((dist, title))

In [95]:
distances.sort(key=lambda x: x[0], reverse=True)
distances[:6]

[(1.0, 'Casablanca'),
 (0.2759243614485557, 'Domestic Disturbance'),
 (0.26635991724620767, 'Rick'),
 (0.2245411041964508, 'Strays'),
 (0.19471363943565267, 'The Principal'),
 (0.18998009350780076, 'Double Tap')]

With a dataframe over comments' collection, find the first 5 users with the larger number of comments. Reperat with aggregate function in MongoDB

In [ ]:
comments = db.comments.find()
df_comments = pd.DataFrame(comments)

In [ ]:
df_comments.head()

,_id,name,email,movie_id,text,date
0,5a9427648b0beebeb69579e7,Mercedes Tyler,mercedes_tyler@fakegmail.com,573a1390f29313caabcd4323,Eius veritatis vero facilis quaerat fuga tempo...,2002-08-18 04:56:07
1,5a9427648b0beebeb69579f5,John Bishop,john_bishop@fakegmail.com,573a1390f29313caabcd446f,Id error ab at molestias dolorum incidunt. Non...,1975-01-21 00:31:22
2,5a9427648b0beebeb6957a21,Jaqen H'ghar,tom_wlaschiha@gameofthron.es,573a1390f29313caabcd516c,Minima odit officiis minima nam. Aspernatur id...,1981-11-08 04:32:25
3,5a9427648b0beebeb6957a22,Taylor Scott,taylor_scott@fakegmail.com,573a1390f29313caabcd4eaf,Iure laboriosam quo et necessitatibus sed. Id ...,1970-11-15 05:54:02
4,5a9427648b0beebeb6957a38,Yara Greyjoy,gemma_whelan@gameofthron.es,573a1390f29313caabcd587d,Nobis incidunt ea tempore cupiditate sint. Ita...,2012-11-26 11:00:57

In [ ]:
occurences = df_comments.groupby(['name', 'email'])['text'].count()
print(type(occurences))
occurences.head()

<class 'pandas.core.series.Series'>

name            email
Aaron Church    aaron_church@fakegmail.com        2
Alliser Thorne  owen_teale@gameofthron.es       201
Amanda Delgado  amanda_delgado@fakegmail.com      2
Amanda Hill     amanda_hill@fakegmail.com         1
Amanda Jordan   amanda_jordan@fakegmail.com       2
Name: text, dtype: int64

In [ ]:
df_occ = pd.DataFrame(occurences)
df_occ

                                                text
name              email
Aaron Church      aaron_church@fakegmail.com       2
Alliser Thorne    owen_teale@gameofthron.es      201
Amanda Delgado    amanda_delgado@fakegmail.com     2
Amanda Hill       amanda_hill@fakegmail.com        1
Amanda Jordan     amanda_jordan@fakegmail.com      2
...                                              ...
Viserys Targaryen harry_lloyd@gameofthron.es     233
Yara Greyjoy      gemma_whelan@gameofthron.es    212
Ygritte           rose_leslie@gameofthron.es     220
Yolanda Owen      yolanda_owen@fakegmail.com     201
Yvette Roth       yvette_roth@fakegmail.com      242

[234 rows x 1 columns]

In [ ]:
df_occ.sort_values('text', ascending=False)[:5]

                                                        text
name             email
Mace Tyrell      roger_ashton-griffiths@gameofthron.es   277
The High Sparrow jonathan_pryce@gameofthron.es           260
Rodrik Cassel    ron_donachie@gameofthron.es             260
Missandei        nathalie_emmanuel@gameofthron.es        258
Robert Jordan    robert_jordan@fakegmail.com             257

In [ ]:
# count for each email the message number, then sort and show firsts 5
group_stg = {"$group":{"_id":"$email", "count":{"$sum":1}}}
sort_stg = {"$sort": {"count":-1}}
limit_stg = {"$limit":5}
list(db.comments.aggregate([group_stg, sort_stg, limit_stg]))

[{'_id': 'roger_ashton-griffiths@gameofthron.es', 'count': 277},
 {'_id': 'ron_donachie@gameofthron.es', 'count': 260},
 {'_id': 'jonathan_pryce@gameofthron.es', 'count': 260},
 {'_id': 'nathalie_emmanuel@gameofthron.es', 'count': 258},
 {'_id': 'robert_jordan@fakegmail.com', 'count': 257}]